#!/usr/bin/env bash
# R09 Task A (TabDataStore backup-cleanup fix) — AC4
# "Positive/negative control differentiate on functional test outcome for the backup-cleanup
#  requirement specifically."
# Method (runnable): this script injects a self-contained XCTest into
# BrowserKit/Tests/TabDataStoreTests/ that seeds MockTabFileManager with a window UUID present
# in the (shared) directory listing, calls removeWindowData(forUUIDs:), and asserts that
# removeFileAt(path:) was called for BOTH the primary and the backup directory lookup — i.e. that
# fileManager.removeFileAtPathCalledCount == 2. It also asserts that removing a window with no
# backup file present does not throw/crash. This test is independent of whatever tests (if any)
# the submitted diff itself adds, so it is a true functional regression guard for this specific
# requirement, not just a check that "some test" exists.
set -uo pipefail

REPO="${1:-.}"
REPO="$(cd "$REPO" 2>/dev/null && pwd)"
BK="$REPO/BrowserKit"

if [ ! -d "$BK" ]; then
  echo "FAIL: AC4 - BrowserKit directory not found at $BK"
  exit 1
fi

TEST_DIR="$BK/Tests/TabDataStoreTests"
if [ ! -d "$TEST_DIR" ]; then
  echo "FAIL: AC4 - $TEST_DIR not found"
  exit 1
fi

TEST_FILE="$TEST_DIR/AC4RegressionTests.swift"

if [ -f "$TEST_FILE" ]; then
  echo "FAIL: AC4 - $TEST_FILE already exists; refusing to overwrite. Remove it and re-run."
  exit 1
fi

cleanup() { rm -f "$TEST_FILE"; }
trap cleanup EXIT

cat > "$TEST_FILE" <<'SWIFT_EOF'
// Auto-generated by validators/task_A_AC4.sh — not part of the submitted solution.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

import XCTest
import TestKit
@testable import TabDataStore

final class AC4RegressionTests: XCTestCase, @unchecked Sendable {
    private let uuidToRemove = UUID(uuidString: "E3FF60DA-D1E7-407B-AA3B-130D48B3909D")!
    private let otherUUID = UUID(uuidString: "ABFF60DA-D1E7-407B-AA3B-130D48B31012")!

    func testRemoveWindowData_removesBothPrimaryAndBackupFiles() async throws {
        let mockFileManager = MockTabFileManager()
        mockFileManager.primaryDirectoryURL = URL(string: "some/primary")
        mockFileManager.backupDirectoryURL = URL(string: "some/backup")
        // MockTabFileManager.contentsOfDirectory(at:) returns this same list regardless of which
        // directory URL is passed in, so seeding it once here simulates "this window's file exists
        // in both the primary and backup directory listings".
        mockFileManager.pathContents = [
            URL(string: "some/primary/window-\(uuidToRemove.uuidString)")!,
            URL(string: "some/primary/window-\(otherUUID.uuidString)")!
        ]

        let subject = DefaultTabDataStore(fileManager: mockFileManager, throttleTime: 100)

        await subject.removeWindowData(forUUIDs: [uuidToRemove])

        XCTAssertEqual(
            mockFileManager.removeFileAtPathCalledCount,
            2,
            "Expected removeFileAt(path:) once for the primary-directory match and once for the " +
            "backup-directory match; got \(mockFileManager.removeFileAtPathCalledCount). This means " +
            "backup files are not being cleaned up alongside primary files."
        )
    }

    func testRemoveWindowData_noBackupFilePresent_doesNotThrowOrCrash() async throws {
        let mockFileManager = MockTabFileManager()
        mockFileManager.primaryDirectoryURL = URL(string: "some/primary")
        mockFileManager.backupDirectoryURL = URL(string: "some/backup")
        // Only the primary directory has a matching file; the backup directory listing is empty.
        mockFileManager.pathContents = [URL(string: "some/primary/window-\(uuidToRemove.uuidString)")!]

        let subject = DefaultTabDataStore(fileManager: mockFileManager, throttleTime: 100)

        await subject.removeWindowData(forUUIDs: [uuidToRemove])

        XCTAssertGreaterThanOrEqual(mockFileManager.removeFileAtPathCalledCount, 1)
    }

    func testRemoveWindowData_untouchedWindow_isNotRemovedFromEitherDirectory() async throws {
        let mockFileManager = MockTabFileManager()
        mockFileManager.primaryDirectoryURL = URL(string: "some/primary")
        mockFileManager.backupDirectoryURL = URL(string: "some/backup")
        mockFileManager.pathContents = [URL(string: "some/primary/window-\(otherUUID.uuidString)")!]

        let subject = DefaultTabDataStore(fileManager: mockFileManager, throttleTime: 100)

        // Removing a UUID that isn't present should not touch the unrelated window's files.
        await subject.removeWindowData(forUUIDs: [uuidToRemove])

        XCTAssertEqual(mockFileManager.removeFileAtPathCalledCount, 0)
    }
}
SWIFT_EOF

# NOTE: plain `swift test` does not work in this environment — the `Common` BrowserKit target
# unconditionally `import UIKit`, and a bare `swift build`/`swift test` picks the host macOS SDK
# (no UIKit) rather than an iOS SDK. `xcodebuild test` against the auto-generated per-target
# scheme (SwiftPM packages opened by Xcode get one scheme per library/test target) targeting an
# iOS Simulator destination is the equivalent, actually-runnable way to execute the same
# TabDataStoreTests test target on this machine.
SIM_NAME=$(xcrun simctl list devices available 2>/dev/null | grep -m1 'iPhone' | sed -E 's/^[[:space:]]*([A-Za-z0-9 ]+) \(.*/\1/')
SIM_NAME="${SIM_NAME:-iPhone 17}"

pushd "$BK" >/dev/null || exit 1
OUTPUT=$(xcodebuild test \
  -scheme TabDataStore \
  -destination "platform=iOS Simulator,name=$SIM_NAME" \
  -only-testing:TabDataStoreTests/AC4RegressionTests \
  2>&1)
STATUS=$?
popd >/dev/null

echo "$OUTPUT" | tail -80

if [ "$STATUS" -eq 0 ] && echo "$OUTPUT" | grep -q '\*\* TEST SUCCEEDED \*\*'; then
  echo "PASS: AC4 - injected backup-cleanup regression test suite passed (removeWindowData removes matching files from both primary and backup directories; no-backup and untouched-window cases behave correctly)"
  exit 0
else
  echo "FAIL: AC4 - injected backup-cleanup regression test suite failed or did not compile (see xcodebuild output above)"
  exit 1
fi
